project:
  type: book
  output-dir: docs
  resources:
    - check.R

book:
  title: "STAT243: Data Analysis and Visualization in R"
  author: "Ihor Miroshnychenko"
  date: today
  chapters:
    - index.qmd
    - 01.qmd
    - 02.qmd
    - 03.qmd
    - 04.qmd
    - 05.qmd
    - 06.qmd
    - 07.qmd
    - 08.qmd
    - 09.qmd
    - 10.qmd
    - 11.qmd
    - 12.qmd
    - 13.qmd
    

format:
  html:
    theme:
      - cosmo
      - brand
    number-sections: false

filters:
  - webr



